Portal\PortalBundle\Entity\Announce:
    type: entity
    table: null
    repositoryClass: Portal\PortalBundle\Entity\AnnounceRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: '100'
        content:
            type: string
            length: '1000'
        address:
            type: string
            length: 255
        created:
            type: datetime
            columnDefinition: TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    manyToOne:
        categoryId:
            targetEntity: Portal\PortalBundle\Entity\Category
            joinColumn:
            name: categoryId
            referencedColumnName: id
        userId:
            targetEntity: Portal\PortalBundle\Entity\User
            joinColumn:
            name: userId
            referencedColumnName: id
    lifecycleCallbacks: {  }