<?php

namespace Portal\PortalBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AnnounceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnnounceRepository extends EntityRepository
{
}
